Doc set event
Genentech/psborrow pull request #46
Opened 2022-04-20 16:08 UTC by gowerc

Closes #25

2022-04-20 16:09 UTC, gowerc commented
@mattsecrest ,  Just to clarify there are no code changes here all I did was re-flow the code to make it more readable. All changes were purely in the documentation

2022-04-21 21:16 UTC, mattsecrest requested changes

2022-04-21 21:16 UTC, mattsecrest commented on R/add_time.R
> +#' @param beta covariates' coefficients. Must be equal in length to the number of covariates
@gowerc I wonder if it's worth clarifying that the `beta` are not exponentiated? The user guide uses values that are all reasonable for HRs, and the default value of 1 I think could also be interpreted that way.

2022-04-27 20:28 UTC, mattsecrest approved these changes

2022-04-27 20:32 UTC, mattsecrest commented
@gowerc made a small change myself, will leave you to review and approve.

2022-04-29 09:36 UTC, merged