WIP - Functions/documentation to run user analysis
Genentech/psborrow pull request #50
Opened 2022-04-22 15:57 UTC by gowerc

2022-04-29 11:35 UTC, gowerc commented
@mattsecrest ,  Added a vignette as well now. I expanded the scope of this to also include #4  as I felt they were strongly connected when writing the file. I took most of the text for the model details directly from the [publication](https://higherlogicdownload.s3.amazonaws.com/AMSTAT/fa4dd52c-8429-41d0-abdf-0011047bfa19/UploadedImages/BIOP%20Report/BioPharmSummer2021_FINAL.pdf) though I think its worth just double checking that we (Roche/Gene) own the copyright for this (@danielinteractive you don't know do you?), if not I will need to rewrite it...

2022-04-29 11:38 UTC, danielinteractive commented
@gowerc I am not sure. That might depend on the journal it was published in. I would just reword slightly etc.

2022-05-06 05:07 UTC, mattsecrest requested changes
@gowerc I made some suggestions in PR https://github.com/Genentech/psborrow/pull/54. The only thing I feel strongly about is the wording of the `alpha_cc` and `alpha_ec` in the no-borrowing scenario.

2022-05-09 18:37 UTC, mattsecrest approved these changes

2022-05-09 19:02 UTC, merged